### ISSUE TITLE
crates.io release

### ISSUE THREAD

**Issue by MOZGIII** [r-util/r-efi-string#1]
This create looks great, but I can't find it at crates.io.
How about making a release there?

**Comment by dvdhrm** [comment]
I tagged `v0.1.0` and published a release:

    https://github.com/r-util/r-efi-string/releases/tag/v0.1.0

I also pushed the same version to crates.io:

    https://crates.io/crates/r-efi-string

If there are any issues, let me know!

The `str16::EfiString16` type is still a stub. However, the boxed version of `str16::EfiStr16` works perfectly well and implements `clone`, so it should be a fine substitute until we have the other type implemented.

Thanks
David
